---
#
#   Set default Java provider and version
#
- name: Set default java
  ansible.builtin.copy:
    dest: '/home/idempiere/.jabbarc'
    owner: idempiere
    group: idempiere
    mode: u=rwx,g=rx,o=
    content: |
      {{ java_version }}
  register: installed_java_version

#
#   Install Java via Jabba
#
# - name: Install Java via Jabba
#  ansible.builtin.shell:
#    cmd: |
#      curl -sL https://github.com/shyiko/jabba/raw/master/install.sh | JABBA_COMMAND="install {{ java_version }} -o {{ java_home }}" bash
#  when: installed_java_version.changed

#
#   Set JAVA_HOME
#
- name: Set Java Home
  ansible.builtin.blockinfile:
    marker: "# {mark} ANSIBLE JAVA CONFIG"
    dest: /home/idempiere/.bashrc
    create: yes
    block: |
      export JAVA_HOME={{ java_home }}
      export PATH=$PATH:{{ java_home }}/bin
